export const FEATURE_LEVELS = {
  DOUBT_CHATBOT_LIMITED: 2,
  MULTI_PLAYLIST: 2,
  AI_NOTES_LIMITED: 2,
  STUDY_PLAN: 3,
  AI_NOTES_UNLIMITED: 3,
  STREAK_FREEZE: 3,
  QUIZ_LIMITED: 3,
  FIVE_PLAYLISTS: 4,
  DOUBT_CHATBOT_UNLIMITED: 4,
  PDF_EXPORT: 4,
  CUSTOM_QUIZ: 4,
  COURSE_SHARE: 5,
  LEADERBOARD: 5,
  ANALYTICS: 5,
  STREAK_FREEZE_3: 5,
  UNLIMITED_PLAYLISTS: 7,
  PRIORITY_PROCESSING: 7,
  AI_PERSONA: 7,
  ALL_FEATURES: 10,
  LEGENDARY_BADGE: 10,
  BETA_ACCESS: 10,
};

export const LEVELS = [
  { level: 1,  threshold: 0 },
  { level: 2,  threshold: 200 },
  { level: 3,  threshold: 500 },
  { level: 4,  threshold: 1000 },
  { level: 5,  threshold: 2000 },
  { level: 6,  threshold: 3500 },
  { level: 7,  threshold: 5500 },
  { level: 8,  threshold: 8000 },
  { level: 9,  threshold: 12000 },
  { level: 10, threshold: 20000 },
];
