import React from 'react';
import { Sparkles } from 'lucide-react';

/**
 * Small disclosure badge for AI-generated content.
 * Satisfies transparency requirements (EU AI Act, Google AI Principles).
 *
 * Usage:
 *   <AiBadge />                    → "AI-generated"
 *   <AiBadge label="AI summary" /> → "AI summary"
 */
const AiBadge = ({ label = 'AI-generated', className = '' }) => (
    <span
        className={`inline-flex items-center gap-1 text-[10px] font-semibold text-text-muted opacity-70 select-none ${className}`}
        title="This content was generated by AI and may contain inaccuracies"
    >
        <Sparkles className="w-3 h-3" />
        {label}
    </span>
);

export default AiBadge;
